#ifndef ROBOT_CONFIG_H
#define ROBOT_CONFIG_H

#include <stdint.h>

#define ROBOT_CONFIG_UART_BAUDRATE                 (230400U)

#define ROBOT_CONFIG_ENCODER_COUNTS_PER_MOTOR_REV (1024U)
#define ROBOT_CONFIG_MOTOR_REDUCTION_RATIO        (30U)
#define ROBOT_CONFIG_ENCODER_COUNTS_PER_WHEEL_REV \
  (ROBOT_CONFIG_ENCODER_COUNTS_PER_MOTOR_REV * ROBOT_CONFIG_MOTOR_REDUCTION_RATIO)

#define ROBOT_CONFIG_WHEEL_DIAMETER_M             (0.077f)
#define ROBOT_CONFIG_TRACK_WIDTH_M                (0.196f)
#define ROBOT_CONFIG_WHEEL_BASE_M                 (0.160f)

#define ROBOT_CONFIG_CONTROL_PERIOD_MS            (10U)
#define ROBOT_CONFIG_IMU_PERIOD_MS                (5U)
#define ROBOT_CONFIG_IMU_ODR_HZ                   (224.2f)
#define ROBOT_CONFIG_IMU_ACCEL_LSB_PER_G          (8192.0f)
#define ROBOT_CONFIG_IMU_GYRO_LSB_PER_DPS         (64.0f)
#define ROBOT_CONFIG_STANDARD_GRAVITY_MPS2        (9.80665f)
#define ROBOT_CONFIG_IMU_CALIBRATION_SAMPLES      (400U)
#define ROBOT_CONFIG_IMU_CALIBRATION_TIMEOUT_MS   (10000U)
#define ROBOT_CONFIG_IMU_STALE_TIMEOUT_MS         (20U)
#define ROBOT_CONFIG_IMU_OUTPUT_FILTER_CUTOFF_HZ  (20.0f)
#define ROBOT_CONFIG_IMU_ACCEL_SPIKE_LIMIT_MPS2   (15.0f)
#define ROBOT_CONFIG_IMU_GYRO_SPIKE_LIMIT_RAD_S   (10.0f)
#define ROBOT_CONFIG_IMU_ERROR_BACKOFF_THRESHOLD  (3U)
#define ROBOT_CONFIG_RUNTIME_READY_TIMEOUT_MS      (3000U)
#define ROBOT_CONFIG_COMM_SERVICE_PERIOD_MS       (5U)
#define ROBOT_CONFIG_TELEMETRY_PERIOD_MS          (20U)
#define ROBOT_CONFIG_SAFETY_PERIOD_MS             (100U)
#define ROBOT_CONFIG_MONITOR_PERIOD_MS            (500U)
#define ROBOT_CONFIG_HEALTH_MISS_LIMIT             (3U)

#define ROBOT_CONFIG_PWM_LIMIT                    (4200)
#define ROBOT_CONFIG_BATTERY_DIVIDER_RATIO        (11.0f)
#define ROBOT_CONFIG_ADC_VREF_MV                  (3300U)
#define ROBOT_CONFIG_ADC_MAX_RAW                  (4095U)
#define ROBOT_CONFIG_BATTERY_DIVIDER_NUM          (11U)
#define ROBOT_CONFIG_BATTERY_DIVIDER_DEN          (1U)

#define ROBOT_CONFIG_CMD_TIMEOUT_MS               (500U)

typedef enum {
  ROBOT_STATUS_OK = 0,
  ROBOT_STATUS_CMD_TIMEOUT = 1,
  ROBOT_STATUS_LOW_BATTERY = 2,
  ROBOT_STATUS_FAULT = 3
} RobotStatus;

#endif /* ROBOT_CONFIG_H */
